apiVersion: v1
kind: Pod
metadata:
  name: secrete-env-var-demo
spec:
  containers:
  - name: secrete-env-var-demo
    image: redis
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password